In [44]:
%matplotlib inline
import numpy as np
import os
import glob as glob
import shutil
import zipfile
from PIL import Image
from PIL import ImageOps
from scipy import misc
import matplotlib.pyplot as plt

### read, resize, transform, rename and save images

In [46]:
WIDTH  = 256
HEIGHT = 256
NUM_CHANNELS = 1

IMG_FORMAT=".jpeg"
PATH="../data/LENS/images/"

def unzipfiles():

    # extract files from a zip file and save them to a specified directory
    myzip = zipfile.ZipFile("../data/LENS/temp1.zip", "r")
    myzip.extractall(path = "../data/LENS/pre_train/")
    #for name in myzip.namelist():
    #    print name
    myzip.close()
    
def load_images():   

    counter = 0
    # Image from PIL library can read an image file as image, then we can operate the image, like resize and grayscale.
    imfilelist=[os.path.join(PATH,f) for f in os.listdir(PATH) if f.endswith(IMG_FORMAT)]
    print(len(imfilelist))
    
    for el in imfilelist:
        counter = counter + 1
        img = Image.open(el)
        #print img.format, img.size, img.mode
        #img = img.convert('L')
        #img = img.resize((WIDTH, HEIGHT), resample=2) 

        #img1 = ImageOps.flip(img)
        img2 = ImageOps.mirror(img)
        #img3 = img.rotate(90)
        #img4 = img.rotate(-90)
        
        '''
        fig, ax = plt.subplots(nrows=2, ncols=3, sharex=True, sharey=True, figsize=(20,8))
        ax = ax.flatten()
        ax[0].imshow(img, cmap='gray')
        ax[1].imshow(img1, cmap='gray')
        ax[2].imshow(img2, cmap='gray')
        ax[3].imshow(img3, cmap='gray')
        ax[4].imshow(img4, cmap='gray')
        plt.tight_layout()
        plt.show()
        
        '''
        img2.save("../data/LENS/augment/origmirror" + str(counter) + ".jpeg")
        
def copyfiles():
    
    for file in glob.glob('../data/LENS/train_ae/*.jpeg'):
        shutil.copy(file, '../data/LENS/augment/')
        
# archive all files in a specified directory to backup
def zipdir(path):
    
    zipf = zipfile.ZipFile('../data/LENS/databackup.zip', 'w', zipfile.ZIP_DEFLATED)
    # ziph is zipfile handle
    for root, dirs, files in os.walk(path):
        for file in files:
            zipf.write(os.path.join(root, file))
    zipf.close()

In [47]:
#load_images()
#copyfiles()
#zipdir('../data/LENS/train_ae/')

In [4]:
# delete an unempty directory
#shutil.rmtree("../data/LENS/pre_train")

In [73]:
def iterate_minibatches(inputs, batchsize, shuffle=False):
    if shuffle:
        indices = np.arange(len(inputs))
        np.random.shuffle(indices)
        print(indices)
    for start_idx in range(0, len(inputs) - batchsize + 1, batchsize):
        if shuffle:
            excerpt = indices[start_idx:start_idx + batchsize]
        else:
            excerpt = slice(start_idx, start_idx + batchsize)
            #print(excerpt)
        yield inputs[excerpt]

In [77]:
inputs = [10, 12, 15, 18, 20, 25, 23, 26, 31]
inputs = np.array(inputs)
for batch in iterate_minibatches(inputs, 3, shuffle=True):
    print batch

[0 4 5 6 2 3 8 1 7]
[10 20 25]
[23 15 18]
[31 12 26]
